### ISSUE TITLE
problemi nello scaricare da myzanichelli

### ISSUE THREAD

**Issue by sefirothmorpheus** [Tecnologica-Mente/myZanichelli_DRM_Remover#7]
ciao, penso che il myzanichelli-drm-remover non funzioni +.
da booktab, ricevo questo errore:

Traceback (most recent call last):
  File "C:\Users\...\Desktop\My Zanichelli\myZanichelli_DRM_Remover-main\download_booktab.py", line 103, in <module>
    entry = config_json['unit']['filesMap']['entry']
KeyError: 'filesMap'

da myzanichelli, ricevo invece questo errore:

1","descr":"LINGUA CINESE SUPERIORI","group":38}]; myz_token=qqnanzotykmm; lastVisitedHosts={"1932696":["my.zanichelli.it"]}; _ga_M3CF5M6GK8=GS1.1.1710856699.3.1.1710856729.0.0.0; stack2=["my.zanichelli.it","webreader.zanichelli.it"]; _gat_UA-41749706-1=1; OptanonConsent=isGpcEnabled=0&datestamp=Tue+Mar+19+2024+19%3A29%3A38+GMT%2B0530+(India+Standard+Time)&version=202310.2.0&browserGpcFlag=0&isIABGlobal=false&hosts=&consentId=49e24637-d194-471f-ba98-d4c0fd590c5a&interactionCount=1&landingPath=NotLandingPage&groups=C0001%3A1%2CC0003%3A1%2CC0004%3A1%2CC0002%3A1&geolocation=IN%3BTN&AwaitingReconsent=false; _ga_FL8QBN8HHQ=GS1.1.1710856699.6.1.1710856779.0.0.0; _ga_HLT0GPY74V=GS1.1.1710856733.4.1.1710856779.0.0.0; _ga_H75ERVB8TD=GS1.1.1710856734.4.1.1710856803.0.0.0; _ga=GA1.2.1785355940.170779 is not a legal HTTP header value
    at validateValue (C:\Users\...\Desktop\My Zanichelli\myZanichelli_DRM_Remover-main\node_modules\node-fetch\lib\index.js:684:9)
    at Headers.append (C:\Users\...\Desktop\My Zanichelli\myZanichelli_DRM_Remover-main\node_modules\node-fetch\lib\index.js:836:3)
    at new Headers (C:\Users\...\Desktop\My Zanichelli\myZanichelli_DRM_Remover-main\node_modules\node-fetch\lib\index.js:761:11)
    at new Request (C:\Users\...\Desktop\My Zanichelli\myZanichelli_DRM_Remover-main\node_modules\node-fetch\lib\index.js:1231:19)
    at C:\Users\...\Desktop\My Zanichelli\myZanichelli_DRM_Remover-main\node_modules\node-fetch\lib\index.js:1449:19
    at new Promise (<anonymous>)
    at fetch (C:\Users\...\Desktop\My Zanichelli\myZanichelli_DRM_Remover-main\node_modules\node-fetch\lib\index.js:1447:9)
    at file:///C:/Users/.../Desktop/My%20Zanichelli/myZanichelli_DRM_Remover-main/download_kitaboo.js:53:22
    at file:///C:/Users/.../Desktop/My%20Zanichelli/myZanichelli_DRM_Remover-main/download_kitaboo.js:132:3

potresti dare un'occhiata e magari aggiornare il tool?
grazie

p.s.
ho provato anche col pdf grabber, ma niente, da zanichelli non riesce a scaricare.

**Comment by Tecnologica-Mente** [comment]
Ciao, ti confermo che myZanichelli DRM Remover è stato bloccato diverso tempo fa.
Per il momento l'unico tool che funziona è pdfgrabber, ma se anche questo non va dovrai attendere una nuova versione dall'autore. Per il momento io non ho tempo di occuparmene.
Saluti
